baseURL: https://etheriamagazine.com/
capitalizeListTitles: false
enableEmoji: true
enableGitInfo: true
defaultContentLanguage: es
removePathAccents: true
summaryLength: 25
title: Etheria Magazine â€” La revista de las mujeres viajeras

build:
  buildStats:
    enable: true

frontmatter:
  lastmod:
    - lastmod
    - date

markup:
  _merge: deep

module:
  imports:
    - path: github.com/etheriamagazine/hugo-modules/sky-theme

permalinks:
  page:
    posts: /articulos/:contentbasename
    pages: :contentbasename
  taxonomy:
    categories: /categorias
    authors: /autoras
  term:
    categories: /:slug
    authors: /autoras/:slug

taxonomies:
  author: authors
  category: categories
  tag: tags

privacy:
  youTube:
    privacyEnhanced: true
