# main menu
main:


  - name: Viajar con amigas
    identifier: amigas
    pageRef: categories/viajar-con-amigas
    weight: 1
  - name: España
    identifier: amigas_1
    pageRef: categories/viajar-con-amigas/españa
    parent: amigas
  - name: Europa
    identifier: amigas_2
    pageRef: categories/viajar-con-amigas/europa
    parent: amigas
  - name: Mundo
    identifier: amigas_3
    pageRef: categories/viajar-con-amigas/mundo
    parent: amigas


  - name: Viajar en familia
    identifier: familia
    pageRef: categories/viajar-en-familia
    weight: 2
  - name: España
    identifier: familia_1
    pageRef: categories/viajar-en-familia/españa
    parent: familia
  - name: Europa
    identifier: familia_2
    pageRef: categories/viajar-en-familia/europa
    parent: familia
  - name: Mundo
    identifier: familia_3
    pageRef: categories/viajar-en-familia/mundo
    parent: familia


  - name: Viajar en pareja
    identifier: pareja
    pageRef: categories/viajar-en-pareja
    weight: 3
  - name: España
    identifier: pareja_1
    pageRef: categories/viajar-en-pareja/españa
    parent: pareja
  - name: Europa
    identifier: pareja_2
    pageRef: categories/viajar-en-pareja/europa
    parent: pareja
  - name: Mundo
    identifier: pareja_3
    pageRef: categories/viajar-en-pareja/mundo
    parent: pareja


  - name: Viajar sola
    identifier: sola
    pageRef: categories/viajar-sola
    weight: 4
    params:
      collapse: true
  - name: España
    pageRef: categories/viajar-sola/españa
    parent: sola
  - name: Europa
    pageRef: categories/viajar-sola/europa
    parent: sola
  - name: Mundo
    pageRef: categories/viajar-sola/mundo
    parent: sola




  - name: Estilo de vida
    identifier: estilo
    pageRef: "categories/estilo-de-vida"
    weight: 5
  - name: Cultura
    pageRef: categories/cultura
    parent: estilo
  - name: Gourmet
    pageRef: categories/gourmet
    parent: estilo
  - name: Hoteles
    pageRef: categories/hoteles
    parent: estilo
  - name: Lujo
    pageRef: categories/lujo
    parent: estilo
  - name: Bienestar
    pageRef: categories/bienestar
    parent: estilo
  - name: Compras
    pageRef: categories/compras
    parent: estilo
  - name: Ocio
    pageRef: categories/ocio
    parent: estilo


  - name: Organiza
    identifier: organiza
    pageRef: "categories/organiza-tu-viaje"
    weight: 6
  - name: Qué llevar en la maleta
    pageRef: categories/que-llevar-en-la-maleta
    parent: organiza
  - name: Guías de destino
    pageRef: categories/guias-de-destino
    parent: organiza
  - name: Excursiones
    pageRef: categories/excursiones
    parent: organiza
  - name: Sorteos
    pageRef: categories/sorteos
    parent: organiza


  - name: Entre mujeres
    identifier: mujeres
    pageRef: ""
    weight: 7
  - name: Mujeres Top
    pageRef: categories/mujeres-top
    parent: mujeres
  - name: Historias en femenino
    pageRef: categories/historias-en-femenino
    parent: mujeres
  - name: Equipo Etheria
    pageRef: equipo-editorial
    parent: mujeres
    weight: 3



footer:
  - name: Aviso legal
    pageRef: pages/aviso-legal
    weight: 1
  - name: Política de privacidad
    pageRef: pages/politica-de-privacidad
    weight: 2
  - name: Política de cookies
    pageRef: pages/politica-de-cookies
    weight: 3
