gitinfo:
  repositoryUrl: https://github.com/etheriamagazine/etheriamagazine.com
  contentRoot: content

imgproxy:
  enabled: true
  host: https://imgp.etheriamagazine.com/
  sourceStyle: encoded
  format: avif
  process: rs:fit:768
  responsive:
    enabled: true
    srcset:
      - size: 640w
        process: rs:fit:640
      - size: 768w
        process: rs:fit:768
      - size: 1024w
        process: rs:fit:1024
      - size: 1280w
        process: rs:fit:1280

plausible:
  enable: true
  domain: etheriamagazine-com.fly.dev
  proxy: true
  proxyPath: /proxyjs
  optional:
    local: true
    fileDownloads: true
    outboundLinks: true
    error404: true
    customEvents: true
    customProps: true

seo:
  author: Etheria Magazine
  titleFormat: "%s â€” %s"
  description: La revista de las mujeres viajeras
  image: logo-que-seguro-que-no-existe.svg
  social:
    instagram: etheriamagazine
    x: etheriamagazine
    facebook: etheriamagazine
    pinterest: etheriamagazine
    github: etheriamagazine

subscribe:
  action: /newsletter
