gitinfo:
  repositoryUrl: https://github.com/etheriamagazine/etheriamagazine.com
  contentRoot: content

imgproxy:
  enabled: true
  host: https://imgp.etheriamagazine.com/
  sourceStyle: plain
  responsive:
    defaultSize: 900
    responsiveSizes:
      - 600
      - 900
      - 1200
    processingOptions: rs:fit:%s
    format: avif

plausible:
  enable: true
  domain: etheriamagazine-com.fly.dev
  proxy: true
  proxyPath: /proxyjs
  optional:
    local: true
    fileDownloads: true
    outboundLinks: true
    error404: true
    customEvents: true
    customProps: true

seo:
  author: Etheria Magazine
  titleFormat: "%s â€” %s"
  description: La revista de las mujeres viajeras
  image: logo-que-seguro-que-no-existe.svg
  social:
    instagram: etheriamagazine
    x: etheriamagazine
    facebook: etheriamagazine
    pinterest: etheriamagazine
    github: etheriamagazine

subscribe:
  action: /newsletter
